name: My First Workflow
on: push

jobs:
    myfirst_job:
        runs-on: ubuntu-20.04
        steps:
        - name: Welcome message
          run: echo "My first Github Actions Job"
        - name: List files
          run: ls
        - name: Read the file
          run: cat README.md