name: trigger workflow with various inputs

on:
    workflow_dispatch:
        inputs:
            run-tests:
                description: "Run tests?"
                type: boolean
                required: true
            test-type:
                description: "Type of test to run?"
                type: choice
                options:
                - unit
                - integration
                - all
                required: true
            environment:
                description: "Choose an environment"
                required: true
                type: environment
            build-number:
                description: "Custom build number"
                type: number
                required: false
            message:
                description: "Additional message"
                type: string
                required: false


jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Print workflow inputs
              run: |
                echo "Run test ${{ inputs.run-tests }}"
                echo "Test type ${{ inputs.test-type }}"
                echo "Environment ${{ inputs.environment}}"
                echo "Message ${{ inputs.message }}"
            
            - name: Run test if selected
              if: ${{ inputs.run-tests == true }}
              run: echo "Testing......"

            # - name: Deploy to ${{ inputs.environment }}
            #   environment: ${{ inputs.envvironment }}