name: Ascii generation
on: push
## multiple jobs will run parallely in different machines
jobs:
    build_job1:
        runs-on: ubuntu-latest
        steps:
        - name: Install cowsay
          run: sudo apt-get install cowsay -y
        - name: Execute cowsay commad
          run: cowsay -f DRAGON "Run for cover, I am DRAGON...RAWR" >> dragon.txt
        - name: sleep for 30 seconds
          run: sleep 30
    
    test_job2:
        needs: build_job1
        runs-on: ubuntu-latest
        steps:
        - name: sleep for 10 seconds
          run: sleep 10
        - name: test file exists
          run: grep -i "dragon" dragon.txt
    
    deploy_job3:
        needs: [build_job1, test_job2]
        runs-on: ubuntu-latest
        steps:
        - name: read file
          run: echo dragon.txt
        - name: deploy file
          run: echo "Deploying file.. .."