name: Working with artifacts
on: push
## multiple jobs will run parallely in different machines
## all three jobs run on their own and file from job will not be automatically shared to the other jobs
jobs:
    build_job1:
        runs-on: ubuntu-latest
        steps:
        - name: Install cowsay
          run: sudo apt-get install cowsay -y
        - name: Execute cowsay commad
          run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt
        - name: upload artifacts so that they can be used in other jobs
          uses: actions/upload-artifact@v4
          with:
            name: dragon text file
            path: dragon.txt
    
    test_job2:
        needs: build_job1
        runs-on: ubuntu-latest
        steps:
        - name: download the file from previous job
          uses: actions/download-artifact@v4
          with:
            name: dragon text file

        - name: test file exists
          run: grep -i "dragon" dragon.txt
    
    deploy_job3:
        needs: test_job2
        runs-on: ubuntu-latest
        steps:
        - name: download the file from previous job
          uses: actions/download-artifact@v4
          with:
            name: dragon text file
        - name: read file
          run: echo dragon.txt
        - name: deploy file
          run: echo "Deploying file.. .."